In [1]:
import numpy as np
def mul_matrix():
    '''this function returns a matrix which is a multiplication result of two matrices'''
    lst1 = []
    lst2 = []
    a = int(input("enter row size of matrix1:"))
    b = int(input("enter column size of matrix1:"))
    i = 0
    while i < a*b:
        lst1.append(int(input("enter values for matrix1:")))
        i = i+1
    print('matrix 1 is :')
    arr1 = (np.array(lst1).reshape(a,b)) 
    print(arr1)
    c = int(input("enter row size of matrix2:"))
    d = int(input("enter column size of matrix2:"))
    j = 0
    while j < c*d:
        lst2.append(int(input("enter values for matrix2:")))
        j = j+1
    print('matrix 2 is :')
    arr2 = (np.array(lst2).reshape(c,d)) 
    print(arr2)
    if b != c:
        print("columns are not equal")
    if b == c:
        print("result is")
        print(arr1.dot(arr2))


In [2]:
mul_matrix()

enter row size of matrix1:3
enter column size of matrix1:3
enter values for matrix1:1
enter values for matrix1:2
enter values for matrix1:3
enter values for matrix1:4
enter values for matrix1:5
enter values for matrix1:6
enter values for matrix1:7
enter values for matrix1:8
enter values for matrix1:9
matrix 1 is :
[[1 2 3]
 [4 5 6]
 [7 8 9]]
enter row size of matrix2:3
enter column size of matrix2:3
enter values for matrix2:9
enter values for matrix2:8
enter values for matrix2:7
enter values for matrix2:6
enter values for matrix2:5
enter values for matrix2:4
enter values for matrix2:3
enter values for matrix2:2
enter values for matrix2:1
matrix 2 is :
[[9 8 7]
 [6 5 4]
 [3 2 1]]
result is
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
